name: Docker in docker Service Example

on:
  push:
    branches:
    - main
  workflow_dispatch:


jobs:
  container-job:
    runs-on: self-hosted

    # runs all of the steps inside the specified container rather than on the VM host.
    # Because of this the network configuration changes from host based network to a container network.
    container:
      image:  registry.gitlab.com/sag-trendminer/containers/container-images/docker-maven:latest
      credentials:
           username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
           password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - run: docker info
